config/routes.rb
Rails.application.routes.draw do
  
    resources :categories
	get "signin" => "sessions#new" 
	resource :session

	get "signup" => "users#new"
	resources :users
  
    root "events#index"

    get "events/filter/:scope" => "events#index", as: :filtered_events 

	resources :events do
		resources :registrations
		resources :likes
	end
	
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event	

  
  validates :name, presence: true

  validates :email, presence: true, format: /\A\S+@\S+\z/, uniqueness: { case_sensitive: false }

	def self.authenticate(email, password)
		user = User.find_by(email: email)
		user && user.authenticate(password)	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_signin, except: [:new,:create] 
	before_action :require_correct_user, only: [:edit, :update, :destroy]

	def index
		@users = User.all 
	end

	def show
		@user = User.find(params[:id])
		@registrations = @user.registrations
		@liked_events = @user.liked_events
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user), notice: "Account successfully Created!"
		else
			render :new
		end
	end

	def edit
		# @user = User.find(params[:id])
	end

	def update
		# @user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to user_path(@user), notice: "Account successfully updated!"
		else
			render :edit
		end
	end

	def destroy
		# @user = User.find(params[:id])
		@user.destroy
		session[:user_id] = nil
		redirect_to users_path, notice: "Your Account successfully Deleted!"
	end

	private

		def require_correct_user
			@user = User.find(params[:id])
			unless current_user?(@user)
				redirect_to root_url
			end

		end
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f|%>
	<p>
		<%=f.label :name %><br/>
		<%= f.text_field :name, size: 40, autofocus: true %>
	</p>

	<p>
		<%=f.label :email %><br/>
		<%= f.text_field :email, size: 40 %>
	</p>

	<p>
		<%=f.label :password %><br/>
		<%= f.password_field :password, size: 40 %>
	</p>

	<p>
		<%=f.label :password_confirmation, "Confirme Password" %><br/>
		<%= f.password_field :password_confirmation, size: 40 %>
	</p>

	<% if @user.new_record? %>
		<%=f.submit "Create Account" %>	
	<%else%>
		<%=f.submit "Update Account" %>
	<%end%>	
	| <%= link_to "Cancel", events_path %>
<%end%>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>

<%= render "shared/errors", object: @user %>
<%= render "form" %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, 'User') %></h1>

<ul>
	<% @users.each do |user| %>
		<li><%=link_to user.name, user %></li> 
	<%end%>	
</ul>

app/views/users/new.html.erb
<h1>Create Your Account </h1>

<%= render "shared/errors", object:@user %>
<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, @user.name)%>
<article>
	<header>
		<h1><%= @user.name%></h1>
		<h5><%= @user.email%></h5>
	</header>
	<% if @registrations.any? %>
		<h3>Registered For</h3>
		<ul>
			<% @registrations.each do |registration|%>
				<li>
					<%= link_to registration.event.name, registration.event %>
					(<%= time_ago_in_words(registration.created_at) %> ago)			
				</li>
			<%end%>
		</ul>	
	<%end%>	

	<%=content_for(:side) do %>
		<%if @liked_events.any?%>
			<h3>Liked Events</h3>
			<ul>
				<%@liked_events.each do |like_event| %>
					<li>
						<%= link_to like_event.name, like_event %>
					</li>
				<%end%>
			</ul>
		<%end%>			
	<%end%>	
</article>

<% if current_user?(@user) %>
	<%= link_to  "Edit Account", edit_user_path(@user) %> | 
	<%= link_to  "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>
<%end%>	