config/routes.rb
Rails.application.routes.draw do
  
    resources :categories
	get "signin" => "sessions#new" 
	resource :session

	get "signup" => "users#new"
	resources :users
  
    root "events#index"

    get "events/filter/:scope" => "events#index", as: :filtered_events 

	resources :events do
		resources :registrations
		resources :likes
	end
	
end

app/models/event.rb
class Event < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :location, :starts_at, presence: true 
	validates :slug, uniqueness: true		

	validates :description, length: {minimum: 15}

	validates :price, numericality: {greater_than_or_equal_to: 0}

	validates :capacity, numericality: {only_integer: true, greater_than: 0}

	validates :image_file_name, allow_blank: true, format: {
		with: /\w+\.(gif|png|jpg)\z/i, message: "must reference a GIF, JPG, or PNG image"	 
	} 

	has_many :registrations, dependent: :destroy 
	has_many :likes, dependent: :destroy
	has_many :likers, through: :likes, source: :user
	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations



	before_validation :generate_slug 

	scope :past, -> { where('starts_at < ?', Time.now).order(:starts_at) }
	scope :upcoming, -> { where("starts_at >= ?", Time.now).order(:starts_at) }
    scope :free, -> { upcoming.where(price: 0).order(:name) }
    scope :recent, ->(max=3){ past.limit(max) } 
    
	def free?
		price.blank? || price.zero? 
	end

	def spots_left
		capacity - registrations.size
	end

	def sold_out?
		spots_left.zero?
	end



	def generate_slug
		self.slug  ||= name.parameterize if name
	end

	def to_param
		slug
	end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	before_action :require_admin,  except: [:index, :show]
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	def index
		case params[:scope]
		when "past"
			@events = Event.past
		when "free"
			@events = Event.free
		when "recent"
			@events = Event.recent
		else		
			@events = Event.upcoming
		end
	end
	
	def show
		@likers = @event.likers
		if current_user
			@current_like = current_user.likes.find_by(event_id: @event.id)
		end
		@categories = @event.categories
	end

	def edit
	end


	def update
		if ( @event.update(event_params) )
			redirect_to @event, notice: "Event successfully updated!" 
		else
			render :edit
		end
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to @event
		else
			render :new
		end	 

	end

	def destroy
		@event.destroy
		redirect_to events_url
	end

	private 

		def set_event
			@event = Event.find_by!(slug: params[:id])
		end
		def event_params
			params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity, category_ids: [])
		end 
end

app/helpers/events_helper.rb
module EventsHelper
	def format_price(event)
		if (event.free?)
			content_tag(:strong, "Free")
		else
			number_to_currency(event.price)
		end	 	
	end

	def image_for(event) 
		if event.image_file_name.blank?
			image_tag "placeholder.png"
		else
			image_tag event.image_file_name
		end 
	end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<%= render "shared/errors", object: @event %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name, autofocus: true %>
	</p>

	<P>
		<%= f.label :description %><br/>
		<%= f.text_area :description %>
	</P>

	<p>
		<%= f.label :location %><br/>
		<%= f.text_field :location %>
	</p>

	<p>
		<%= f.label :price %><br/>
		<%= f.number_field :price %>
	</p>
	
	<p>
		<%= f.label :starts_at %><br/>
		<%= f.datetime_select :starts_at %>
	</p>	

	<p>
		<%= f.label :image_file_name %><br/>
		<%= f.text_field :image_file_name, size: 30, placeholder: "GIF, JPG, or PNG file name" %>
	</p>

	<p>
		<%= f.label :capacity %><br/>
		<%= f.number_field :capacity %>
	</p>

	<p>
		<%= f.label :categories %>:
		<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name)%>
	</p>


	<%= f.submit %> |
	<%= link_to "Cancel", events_path %>

<%end%>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render "form" %>

app/views/events/index.html.erb
<h1><%= pluralize(@events.size, 'Event') %> </h1>

<% @events.each do |event| %>
	<article>
		<header>
			<%= image_for(event) %><br/>	
			<strong> <%=link_to(event.name, event_path(event)) %></strong>
		</header>
		<p>
			<%= truncate(event.description, length: 27, separator: ' ') %>
		</p>
		<table>
			<tr>
				<th>When</th>
				<td><%= event.starts_at %></td>
			</tr>
			
			<tr>
				<th>Where</th>
				<td><%= event.location %></td>
			</tr>
			
			<tr>
				<th>Price:</th>
				<td><%= format_price(event) %></td>
			</tr>

			<tr>
				<th>Capacity:</th>
				<td><%= pluralize(event.spots_left, 'spot') %> available </td>
			</tr>
		</table>
	</article><hr></hr>


<% end %>

app/views/events/new.html.erb
<h1>Create New Event</h1>

<%= render "form" %>

app/views/events/show.html.erb
<% content_for(:title, @event.name) %>
<article>
	<header>
		<%= image_for(@event) %>
		<h1><%=@event.name%></h1>
	</header>
	<p>
		<%= @event.description%>
	</p>
	<h3>When:</h3>
	<P>
		<%= @event.starts_at %>
			
	</P>
	<h3>Where:</h3>
	<P>
		<%= @event.location %>
			
	</P>

	<h3>Price:</h3>
	<P>
		<%= format_price(@event) %>
	</P>
	<h3>Capacity:</h3>
	<p>
		<%= pluralize(@event.capacity, 'spot') %>
	</p>

	<% content_for(:side) do %>	
		<h3>Category:</h3>
		<p>
			<ul>
				<%@categories.each do |category|%>
					<li>
						<%=category.name%>
					</li>	
				<%end%>
			</ul>
		</p>

	
		<h3>Likers:</h3>
		<%if @likers.any? %>
			<p>
				<ul>
					<%@likers.each do |user| %>
						<li>	
							<%=link_to  user.name, user%>
						</li>	
					<%end%>
				</ul>	
			</p>
		<%end%>
	<%end%>	
	<% if @current_like %>
		<%= button_to 'Unlike', event_like_path(@event,@current_like), method: :delete%>
	<%else%>	
		<%= button_to 'Like', event_likes_path(@event)%>
	<%end%>
	<%= link_to "who's registered?", event_registrations_path(@event) %><hr>

</article>
<%=register_link(@event) %> |
<%if current_user_admin? %>
	<%= link_to "Edit", edit_event_path(@event) %> |
	<%= link_to "Delete", event_path(@event), method: :delete, data: {confirm: "Are you sure?"} %><br/>
<%end%>
(<%= pluralize(@event.spots_left, 'spot') %> available)